In [1]:
%load_ext autoreload
%autoreload 2

In [41]:
import open3d as o3d
import numpy as np
import h5py as h5
from plyfile import PlyData, PlyElement
from SorghumPartNet.data.utils import rgb_dec_to_hex 

result_file_path = "/space/murph186/results/BTx_623_1101_330749064044/instance.ply"

plydata = PlyData.read(result_file_path)
print(plydata.elements)
for i in range(len(plydata.elements)):
    print(i,plydata.elements[i].name,plydata.elements[i].data.shape)

data = np.asarray(np.array(plydata.elements[0].data).tolist())

points = data[:, :3]
colors = np.apply_along_axis(rgb_dec_to_hex, 1, (data[:, 3:] / 255))

print(points)
print(colors)
print(np.unique(colors).shape)

(PlyElement('vertex', (PlyProperty('x', 'double'), PlyProperty('y', 'double'), PlyProperty('z', 'double'), PlyProperty('red', 'uchar'), PlyProperty('green', 'uchar'), PlyProperty('blue', 'uchar')), count=2307, comments=[]),)
0 vertex (2307,)
[[-0.10683113  0.177035    0.29429337]
 [-0.29101491  0.41317955  0.10002431]
 [ 0.07400625  0.572007   -0.00379968]
 ...
 [ 0.03630961  0.32718655  0.06216304]
 [-0.00258933  0.26196203 -0.0575931 ]
 [ 0.09389769  0.45742857 -0.32035154]]
[43814  1548 58458 ...  4903  4903 16288]
(34,)


In [42]:
import k3d
print(colors.shape)
print(points.shape)
plot = k3d.plot(name='points')
plt_points = k3d.points(positions=points, point_size=0.01, colors=colors)
plot += plt_points


plt_points.shader='3d'
plot.display()

(2307,)
(2307, 3)


Output()